project_id = "zcybqreiksrgaisnkauj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.maintenance-archive-completed]
    verify_jwt = false
